import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "./store/ReduxProvider";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";
import { Footer } from "@/components/Footer";
import { Suspense } from "react";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <Suspense>
        <ReduxProvider>
          <Navbar/>
          {children}
          <Footer/>
        </ReduxProvider>
        </Suspense>
        <ToastContainer />
      </body>
    </html>
  );
}
